version: "3.8"

services:
  equalishcoind:
    image: debian:stable-slim
    container_name: equalishcoind
    restart: unless-stopped
    command: ["/usr/local/bin/equalishcoind", "-conf=/data/equalishcoin.conf", "-datadir=/data"]
    ports:
      - "19901:19901"
      - "19902:19902"
    volumes:
      - ./data:/data
