description "EqualishCoin Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env EQUALISHCOIND_BIN="/usr/bin/equalishcoind"
env EQUALISHCOIND_USER="equalishcoin"
env EQUALISHCOIND_GROUP="equalishcoin"
env EQUALISHCOIND_PIDDIR="/var/run/equalishcoind"
env EQUALISHCOIND_PIDFILE="/var/run/equalishcoind/equalishcoind.pid"
env EQUALISHCOIND_CONFIGFILE="/etc/equalishcoin/equalishcoin.conf"
env EQUALISHCOIND_DATADIR="/var/lib/equalishcoind"

expect fork
respawn
respawn limit 5 120
kill timeout 600

pre-start script
    mkdir -p "$EQUALISHCOIND_PIDDIR"
    chmod 0755 "$EQUALISHCOIND_PIDDIR"
    chown $EQUALISHCOIND_USER:$EQUALISHCOIND_GROUP "$EQUALISHCOIND_PIDDIR"
    chown $EQUALISHCOIND_USER:$EQUALISHCOIND_GROUP "$EQUALISHCOIND_CONFIGFILE"
    chmod 0660 "$EQUALISHCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$EQUALISHCOIND_PIDFILE" \
    --chuid $EQUALISHCOIND_USER:$EQUALISHCOIND_GROUP \
    --exec "$EQUALISHCOIND_BIN" \
    -- \
    -pid="$EQUALISHCOIND_PIDFILE" \
    -conf="$EQUALISHCOIND_CONFIGFILE" \
    -datadir="$EQUALISHCOIND_DATADIR" \
    -daemon
