name: Build Docker multi-arch image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tags
        id: tags
        run: |
          sha8=$(echo $GITHUB_SHA | cut -c1-8)
          if [[ $GITHUB_REF == refs/heads/master ]]; then
            echo "tags=ghcr.io/${GITHUB_REPOSITORY}/equalishcoind:latest,ghcr.io/${GITHUB_REPOSITORY}/equalishcoind:$sha8" >> $GITHUB_OUTPUT
          else
            echo "tags=ghcr.io/${GITHUB_REPOSITORY}/equalishcoind:$sha8" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: contrib/Dockerfile.nogui
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        id: detect-publish-latest
        if: steps.detect.outputs.tag-name != 'noop' && (github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release-'))
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PUBLISH=noop
          git fetch origin +refs/tags/latest:refs/tags/latest
          if ! git merge-base --is-ancestor refs/tags/latest HEAD; then
            PUBLISH=op
            if gh release list --repo ${{ github.repository }} | grep "latest"; then
              gh release delete latest --cleanup-tag --yes --repo ${{ github.repository }}
            fi
          fi
          echo "publish=$PUBLISH" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        if: steps.detect.outputs.tag-name != 'noop' && startsWith(github.ref, 'refs/tags/v')
        run: |
          git fetch --depth=1 origin +${{ github.ref }}:${{ github.ref }}
          git tag -l --format='%(contents)' ${GITHUB_REF/refs\/tags\//} > ${{ github.workspace }}-CHANGELOG.txt

      - uses: softprops/action-gh-release@v2
        if: steps.detect.outputs.tag-name != 'noop' && steps.detect-publish-latest.outputs.publish == 'op' && (github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release-'))
        with:
          tag_name: ${{ steps.detect.outputs.tag-name }}
          token: ${{ github.token }}
          prerelease: true
          name: "${{ steps.detect.outputs.release-title }}"
          files: ${{ steps.detect.outputs.tag-name }}/*

      - uses: softprops/action-gh-release@v2
        if: steps.detect.outputs.tag-name != 'noop' && startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ steps.detect.outputs.tag-name }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          token: ${{ github.token }}
          prerelease: true
          name: "${{ steps.detect.outputs.release-title }}"
          files: ${{ steps.detect.outputs.tag-name }}/*
